### PR TITLE
Add hashtags to graph

### PR DESCRIPTION
**Pull request by joelmturner**
Allows a user to query by hashtags used in posts. Works only with Graph API. 

This PR solves part of the question raised in  #58 except the user must be credentialed. 

* extracts hashtags from caption
* optionally extracts hashtags from comments
* defaults to false

```javascript
hashtags: true // defaults to false
```

or

```javascript
hashtags: {
  enabled: true, // defaults to false
  commentDepth: 10 // defaults to 3
} 
```

### CODE REVIEW

**Comment by oorestisime** [comment]
Hey thanks for this!
I am currently on holiday until the 26th and won't be able to check this!
Looking forward to merge this when i am back!

**Comment by joelmturner** [comment]
Sounds good! Enjoy your holiday! 😄

**Review by oorestisime — APPROVED** [review]
Hey many thanks for this feature!

Some minor things left if you would like to take care of them:

* Update the how to query section https://github.com/oorestisime/gatsby-source-instagram#how-to-query to add the hashtags 
* this might be more annoying todo just for the setup (check gatsby config on what to do to allow local plugin) and i could do it myself but there's an example project here https://github.com/oorestisime/gatsby-source-instagram/tree/master/example would be nice to include the hashtags somehow so i can easily verify they work in the future.

As i said nothing blocking i can take care of both myself.

**Comment by oorestisime** [comment]
Also given you worked with the graph api i would like your input for https://github.com/oorestisime/gatsby-source-instagram#instagram-graph-api-token
Did you generate the token using this approach? was there anything not working?

**Comment by joelmturner** [comment]
Thank you for the feedback, I was able to get the example and readme updated.

> Also given you worked with the graph api i would like your input for https://github.com/oorestisime/gatsby-source-instagram#instagram-graph-api-token
> Did you generate the token using this approach? was there anything not working?

I followed the directions from the readme a while back (sometime last year, possibly before the latest updates to this section) and had a lot of trouble getting it working at that time. I tried a bunch of different things, but, I don't remember what it was that got it to start working correctly.

**Comment by oorestisime** [comment]
Thanks a ton for the contribution :)

**Pull request merged**
