### PR TITLE
add preview and mediaType to fields & use preview url to create localFile

### PR DESCRIPTION
**Pull request by riencoertjens**
using added preview field to create localFile. fixes query breaking when the mediatype is "VIDEO" because there's no childImageSharp node created for video files

### CODE REVIEW

**Comment by oorestisime** [comment]
This is looking good, i hope to be able to test this tonight.

I am wondering though if we need to introduce a breaking change for that. Is the preview url really needed as a property? Can't we just add `|| datum.thumbnail_url` in the original one?

**Comment by riencoertjens** [comment]
you could do that, but I don't think anything is breaking here? just the localFile will always be an image now, like it was meant to be (I think?).
I might use the original video file further on in my project, that's why I added the preview field.

**Comment by oorestisime** [comment]
ok makes sense! i ll test this asap and merge! thanks again

**Comment by oorestisime** [comment]
:100:  Perfect thanks!

**Pull request merged**
